//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Know.ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genero
    {
        public int Id_Obj { get; set; }
        public string Genero1 { get; set; }
    
        public virtual Objecto Objecto { get; set; }
    }
}
