//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowDesktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbConocimientoEntities : DbContext
    {
        public dbConocimientoEntities()
            : base("name=dbConocimientoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Objecto> Objecto { get; set; }
        public virtual DbSet<Animado> Animado { get; set; }
        public virtual DbSet<Color> Color { get; set; }
    
        public virtual ObjectResult<spConocimiento_Result> spConocimiento(Nullable<int> opc, string nombre)
        {
            var opcParameter = opc.HasValue ?
                new ObjectParameter("Opc", opc) :
                new ObjectParameter("Opc", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConocimiento_Result>("spConocimiento", opcParameter, nombreParameter);
        }
    }
}
